# ~/nixos-config/flake.nix
# Reproducible NixOS configuration — works on any PC with nix flakes.
#
# Quick start on a fresh machine:
#   1. Install NixOS (any desktop install is fine)
#   2. Clone this repo to ~/nixos-config
#   3. Generate hardware config: sudo nixos-generate-config --show-hardware-config > ~/nixos-config/hardware-configuration.nix
#   4. Build: sudo nixos-rebuild switch --flake ~/nixos-config#default
#
# To update (on any machine using this config):
#   sudo nixos-rebuild switch --flake ~/nixos-config#default

{
  description = "Reproducible NixOS configuration with Niri and Home Manager";

  inputs = {
    # Pin nixpkgs for reproducibility
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-25.05";

    # Unstable nixpkgs for packages that need newer versions
    nixpkgs-unstable.url = "github:NixOS/nixpkgs/nixos-unstable";

    # Home Manager for declarative user config
    home-manager = {
      url = "github:nix-community/home-manager/release-25.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Niri — Wayland scrollable-tiling compositor
    niri = {
      url = "github:sodiboo/niri-flake";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # nixos-hardware for optimized hardware support
    nixos-hardware.url = "github:NixOS/nixos-hardware/master";

    # Noctalia shell for Niri
    noctalia = {
      url = "github:noctalia-dev/noctalia";
      # Omit inputs.nixpkgs.follows to use the binary cache (cachix)
    };

    ayugram-desktop = {
          type = "git";
          submodules = true;
          url = "https://github.com/ndfined-crp/ayugram-desktop/";
    };

    # WinApps — run Windows apps on Linux via Podman/Docker
    winapps = {
      url = "github:winapps-org/winapps";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  # Binary cache for Noctalia — skip compiling locally
  nixConfig = {
    extra-substituters = [ "https://noctalia.cachix.org" ];
    extra-trusted-public-keys = [ "noctalia.cachix.org-1:pCOR47nnMEo5thcxNDtzWpOxNFQsBRglJzxWPp3dkU4=" ];
  };

  outputs = { self, nixpkgs, nixpkgs-unstable, home-manager, niri, noctalia, ayugram-desktop, winapps, ... }@inputs:
    let
      # System architecture — change per machine if needed
      system = "x86_64-linux";

      # Helper to add unfree packages across all nixpkgs instances
      mkPkgs = pkgs: extraOverlays: import pkgs {
        inherit system;
        config.allowUnfree = true;
        overlays = extraOverlays;
      };

      pkgs = mkPkgs nixpkgs [ ];
      pkgs-unstable = mkPkgs nixpkgs-unstable [ ];

      # Username — change this if your username differs on another machine
      username = "phouvongviphop";

      # Hostname — override per machine
      hostname = "nixos";

    in {
      nixosConfigurations.default = nixpkgs.lib.nixosSystem {
        inherit system;
        specialArgs = {
          inherit inputs pkgs-unstable username hostname;
        };
        modules = [
          # System-level configuration
          ./modules/system/default.nix

          # Desktop / display configuration
          ./modules/desktop/default.nix

          # Hardware configuration (generated by nixos-generate-config)
          ./hardware-configuration.nix

          # Home Manager as a NixOS module
          home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.backupFileExtension = "backup";
            home-manager.extraSpecialArgs = {
              inherit pkgs-unstable username inputs;
            };
            home-manager.users.${username} = import ./modules/home/default.nix;
          }
        ];
      };

      # Expose packages for `nix run` etc.
      packages.${system}.default = nixpkgs.legacyPackages.${system}.hello;
    };
}
